name: mentor
description: A project of Ptz
publish_to: "ptz"
version: 1.0.0

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2  
  google_fonts: ^6.2.1
  flutter_bloc: ^8.1.1
  adaptive_navigation: ^0.0.9
  go_router: ^14.3.0
  url_launcher: ^6.1.10
  flutter_layout_grid: ^2.0.7
  universal_platform: ^1.0.0+1
  desktop_window: ^0.4.0
  adaptive_breakpoints: ^0.1.6
  adaptive_components: ^0.0.9
  collection: ^1.17.0
  animations: ^2.0.7
  dynamic_color: ^1.6.2
  font_awesome_flutter: ^10.4.0
  intl: ^0.19.0
  flutter_keyboard_visibility: ^6.0.0
  pin_code_fields: ^8.0.1
  flutter_staggered_grid_view: ^0.7.0
  timeago: ^3.7.0
  flutter_timeline: ^0.3.0
  flutter_html: 3.0.0-beta.2
  table_calendar: ^3.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  #flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app-icon.png"
  min_sdk_android: 19 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/app-icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/app-icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/app-icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
#Generate launcher icons `flutter pub run flutter_launcher_icons`
